### ISSUE TITLE
Speed up future development & fixes: Refactor snaps in launchpad state in store [4]

### ISSUE THREAD

**Issue by earnubs** [canonical-ols/build.snapcraft.io#465]
Refactoring of the structure of snaps related data in application store. Meant to improve decoupling of the data and making it easier and quicker to fix bugs and implement new snaps related features in future.

~~Currently blocks progress on #300~~

----

Refactor the `snapBuilds`, `snaps` and `registerName` state to work off a single list  of snaps-in-launchpad, based off whatever best practice established in #464, with the investigation into potential benefits of also merging into the source repositories structure established in #464.

This should be split up further if possible in light of work done in #464.

- [x] ~~refactor `snaps` store - use only `id`s in snaps list, keep snap objects (with their state) in `entities` [1-2 days, should unblock #300]~~ DONE in #624
- [x] ~~refactor snaps related API calls to use new CALL_API middleware (possibly split more into several tasks for each API call or action)~~
  - find snaps API calls already refactored
  - register name API calls are to the store so no need for them to go through middleware
  - snap builds API calls to be refactored separately as part of #639
- [x] ~~refactor snap related API responses to return normalized and camelCased props (just like repo APIs do now)~~ DONE #650
- [x] ~~try moving register name state from `registerName` reducer to snaps objects in entities~~ DONE in #637
  - ~~update ids used by register name actions to be compatible with snap ids (url) and not repo full names as they are now~~
- [x] ~~refactor snap builds - move them to entities? keep builds ids list in snaps in entities? (to be further discussed)~~ MOVED TO #639

**Comment by bartaz** [comment]
This depends on #464, so is blocked until we have more established practices for these refactoring tasks.
