### ISSUE TITLE
Adding snap build status badge to your README [2]

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#675]
Create a [GitHub badge](https://shields.io/) to show the build status of a repository, and provide helper text to help add this to the README of a repository. This helper text should probably be shown on the build status page, next to the instructions for installing the snap from the CLI.

We should also consider telling the user how to add "snap install" instructions to their README at the same time.

---

TODO:
- [x] generate badge images for all the build statues [#727]
- [x] handler for checking latest status for given repo [#734]
- [x] handler for returning proper badge image for given repo [#734]
- [x] display badge on repo page ([spec](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.vhi6nalioput))
- [ ] generate Markdown for badge image with link
- [ ] copy Markdown to clipboard on button click

**Comment by nottrobin** [comment]
The second part of this is covered by #655

**Comment by matthewpaulthomas** [comment]
It might be a little annoying if build.snapcraft.io continued giving you this suggestion, when you had already followed it days or years ago. Would it make sense for build.snapcraft.io to scan the README, and suggest adding the badge only if you hadn’t already? (That might not make sense if, for example, it’s plausible for you to put the graphic in places other than the README too.)

**Comment by matthewpaulthomas** [comment]
[Spec updated](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.vhi6nalioput). Instead of making the instructions dependent on whether you’ve already added the badge, I’ve taken a less finicky approach by putting an icon-only Copy button next to the badge itself.

**Comment by bartaz** [comment]
For implementation: https://github.com/badges/gh-badges

**Comment by bartaz** [comment]
@matthewpaulthomas Spec defines two separate links for two parts of a badge. I've never seen any badge do that and it would be pretty hard to achieve that in Markdown as we are simply dealing with a single image wrapped in a link.

Most badges seem to link to a "project" page listing all the builds (with latest on top) - so that would be our Repo page.

**Comment by matthewpaulthomas** [comment]
@bartaz https://github.com/badges/gh-badges was last modified 3 years ago, and links to http://img.shields.io/, which redirects to http://shields.io/, which says “`?link=http://left&link=http://right` Specify what clicking on the left/right of a badge should do”.

If that’s rare behavior (or if it’s not actually functional), I’ll gladly change the spec so that the whole badge goes to the repo page.

**Comment by bartaz** [comment]
@matthewpaulthomas I've seen shields.io suggesting you could define 2 separate links, but couldn't make it work in any way. And I don't really know how it's meant to work when what they return is just an image...

So I'd suggest going with one link for whole badge, and if at any point we will find an easy way to make it work with 2 links we could always update.

**Comment by bartaz** [comment]
This issue is currently blocked on lack of visual design for copy functionality (copy icon, toolip, etc).

@kwm14 Could you provide missing assets for this? Thanks.

**Comment by matthewpaulthomas** [comment]
[Spec updated](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.vhi6nalioput) as discussed above, with the whole badge linked to the repo page.
